#! /bin/sh
set -e

mv /tmp/kylin.path /etc/gconf/2/path
mv /usr/share/glib-2.0/schemas/org.gnome.nautilus.gschema.xml.old /usr/share/glib-2.0/schemas/org.gnome.nautilus.gschema.xml
mv /usr/share/glib-2.0/schemas/10_nautilus.gschema /usr/share/glib-2.0/schemas/10_nautilus.gschema.override
mv /tmp/%gconf-tree.xml /var/lib/gconf/debian.defaults/%gconf-tree.xml
glib-compile-schemas /usr/share/glib-2.0/schemas/

