#! /bin/sh
set -e

mv /tmp/kylin.path /etc/gconf/2/path
mv /usr/share/glib-2.0/schemas/10_nautilus.gschema /usr/share/glib-2.0/schemas/10_nautilus.gschema.override
glib-compile-schemas /usr/share/glib-2.0/schemas/

