#! /bin/sh
set -e

mv /usr/share/glib-2.0/schemas/10_ubuntu-settings.gschema.override /usr/share/glib-2.0/schemas/10_ubuntu-settings.gschema.override-bak
mv /usr/share/glib-2.0/schemas/org.gnome.nautilus.gschema.xml /usr/share/glib-2.0/schemas/org.gnome.nautilus.gschema.xml-bak
mv /usr/share/glib-2.0/schemas/10_ubuntu-settings.gschema /usr/share/glib-2.0/schemas/10_ubuntu-settings.gschema.override
mv /usr/share/glib-2.0/schemas/org.gnome.nautilus.gschema /usr/share/glib-2.0/schemas/org.gnome.nautilus.gschema.xml
glib-compile-schemas /usr/share/glib-2.0/schemas/


