#!/bin/sh
set -e
package=ubuntukylin-default-settings

files="
usr/share/unity-control-center/ui/UbuntuLogo.png
usr/share/ubiquity/pixmaps/ubuntu_installed.png
usr/share/language-selector/data/pkg_depends
usr/share/unity-control-center/searchingthedashlegalnotice.html
usr/share/unity/icons/searchingthedashlegalnotice.html
"

if [ "$1" = install -o "$1" = upgrade ]; then
	for item in $files; do
		dpkg-divert --package $package --rename --divert "/$item"".orig-brand" --add "/$item"
	done
        sed -i 's/\(NAME="Ubuntu\)"/\1 Kylin"/' /etc/os-release 
        sed -i 's/\(PRETTY_NAME="Ubuntu\) 1/\1 Kylin 1/' /etc/os-release
        rm -f /etc/ubuntukylin-release
        rm -f /usr/share/language-support/incomplete-language-support-gnome.note
fi

#DEBHELPER#

