#!/bin/sh
set -e
package=ubuntukylin-default-settings

files="
usr/share/unity-control-center/ui/UbuntuLogo.png
"

if [ "$1" = install -o "$1" = upgrade ]; then
	for item in $files; do
		dpkg-divert --package $package --rename --divert "/$item"".orig-brand" --add "/$item"
	done
fi

#DEBHELPER#

if [ "$1" = install -o "$1" = upgrade ]; then
    dpkg-divert --package ubuntukylin-default-settings --rename --divert /etc/chromium-browser/default.uk-defaults --add /etc/chromium-browser/default
fi
