#!/bin/sh
set -e
package=ubuntukylin-default-settings

files="
usr/share/unity-control-center/ui/UbuntuLogo.png
usr/share/ubiquity/pixmaps/ubuntu_installed.png
usr/share/language-selector/data/pkg_depends
usr/share/unity-control-center/searchingthedashlegalnotice.html
usr/share/unity/icons/searchingthedashlegalnotice.html
"

if [ "$1" = remove -o "$1" = purge ]; then
	for item in $files; do
		dpkg-divert --package $package --rename --divert "/$item"".orig-brand" --remove "/$item"
	done
        sed -i "/NAME/s/Ubuntu Kylin/Ubuntu/g" /etc/os-release
        rm -f /etc/ubuntukylin-release
        rm -f /usr/share/language-support/incomplete-language-support-gnome.note
fi

#DEBHELPER#

