#!/bin/sh
set -e

# Hook for building live images
#
# This script is run in the built chroot after all packages are installed,
# before it is packed into a squashfs. This is where you can apply extra tweaks
# to the live system.
apt-get purge --auto-remove -y totem 
cp /usr/share/applications/firefox.desktop /etc/skel/桌面/
