#!/bin/sh
set -e
# Automatically added by dh_ubuntu_defaults
if [ "$1" = remove -o "$1" = abort-install -o "$1" = disappear ]; then
    dpkg-divert --package ubuntukylin-default-settings --rename --divert /usr/share/applications/defaults.list.ubuntu-defaults --remove /usr/share/applications/defaults.list
fi
# End automatically added section
